# Generated by Django 5.0.1 on 2024-01-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciontarjeta',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_tarjetas.operaciontarjeta')),
            ],
        ),
    ]
