# Generated by Django 5.0.1 on 2024-01-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tarjetas', '0002_alter_operaciontarjeta_cantidad_cuotas_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('operacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_tarjetas.operaciontarjeta')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuota',
        ),
    ]
