# Generated by Django 5.0.1 on 2024-01-29 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tarjetas', '0005_operaciontarjeta_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontarjeta',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuraciontarjeta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operaciontarjeta',
            name='tarjeta_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='gestor_tarjetas.configuraciontarjeta'),
        ),
    ]
