# Generated by Django 5.0.1 on 2024-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tarjetas', '0006_configuraciontarjeta_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='fecha_cierre_en_operacion',
            field=models.DateField(null=True),
        ),
    ]
